### ISSUE TITLE
appBarWithButton 로직 오류

### ISSUE THREAD

**Issue by NOGUEN** [NewFit/NewFit-App#25]
## 개요
appBarWithButton에 로직 오류가 있습니다.

## 오류
스크롤이 위로 올라가게 되면 유저의 크레딧 정보를 가림과 동시에 그 공간에 어떤 것도 들어가있지 않아야 하는데, 현재 SizedBox가 포함됩니다.
이로 인해 Container 영역을 넘어서 오버플로우가 발생합니다. 

이런 현상은 creditInfo에 세로축 padding으로 사용되는 SizedBox(height: n)이 포함되지 않아서 발생하는 것으로 추정됩니다.

**Comment by Haneol** [comment]
view/equipment_list에서 해당 문제를 해결하였습니다.
_UserCreditInfo 위젯과 SizedBox 위젯에 각각 `scrollPosition.value <= 0.0` 조건을 달아 스크롤업 상태에서 해당 위젯들이 보이지 않도록 설정하였습니다. 

해당 부분 확인 부탁드립니다. issue-25 브랜치에도 push하겠습니다.
