### ISSUE TITLE
kakao 로그인 관련 app package name

### ISSUE THREAD

**Issue by NOGUEN** [NewFit/NewFit-App#38]
카카오 로그인에 등록하기 위해 app package name을 확인해보니, `com.example.newfit`으로 되어있었습니다.

`com.example.newfit`를 `com.newfit.newfit`으로 수정하면서 전체 빌드 파일에 변화가 생겼으니 나중에 pull 해주세요.

**Comment by Haneol** [comment]
서비스 로직 구현 시에 참고하여 브랜치 생성하겠습니다.
